apiVersion: v1
kind: Pod
metadata:
  name: mhaddad-pod-pytorch
spec:
  restartPolicy: Never
  volumes:
    - name: mhaddad-pv-storage
      persistentVolumeClaim:
        claimName: mhaddad-pv-claim
  containers:
    - name: mhaddad-container-pytorch
      image: "nvcr.io/nvidia/pytorch:24.03-py3"  # Change this (Look up at NGC NVIDIA)
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo 'mhaddad-pod log'; sleep 10; done"]
      volumeMounts:
        - mountPath: "/workspace"
          name: mhaddad-pv-storage
